stages:
  - test

cache:
  key: always
  paths:
  - ./.m2


before_script:
  - cp -R ./.m2 $HOME || true


after_script:
  - cp -R $HOME/.m2 .


test:
  image: clojure:openjdk-11-tools-deps-1.10.1.483
  script:
    - clojure -Adev:test
    - clojure -Adev:propertytest
